ethernet_interfaces:
- name: Ethernet1
  description: L2_leaf07_Ethernet4
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: leaf07
  peer_interface: Ethernet4
  peer_type: l3leaf
- name: Ethernet2
  description: L2_leaf08_Ethernet4
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: leaf08
  peer_interface: Ethernet4
  peer_type: l3leaf

port_channel_interfaces:
- name: Port-Channel1
  description: L2_DC1_L3_POD4_Port-Channel4
  shutdown: false
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: 11-12,21-22,31-32,3401-3402
  
vlan_interfaces:
  - name: "Vlan21"
    description: vrf-irb-vlan21
    shutdown: False
    vrf: VRF11
    ipv6_address: "2001:db8:21::204/48"
  - name: "Vlan11"
    description: vrf-irb-vlan11
    shutdown: False
    vrf: VRF10
    ipv6_address: "2602:0010:FF:11::204/64"

ipv6_static_routes:
- vrf: MGMT
  prefix: ::/0
  next_hop: "3fff:172:20:20::1"
- vrf: VRF10
  prefix: ::/0
  next_hop: "2602:0010:FF:11::1"
- vrf: VRF11
  prefix: ::/0
  next_hop: "2001:db8:21::1"