service_routing_protocols_model: multi-agent
ip_routing: true
ipv6_routing: true

#tenants:
#  - name: CUSTOMER
#    vrfs:
#      - name: VRF11



vlan_interfaces:
  - name: "Vlan21"
    description: vrf-irb-vlan21
    shutdown: False
    vrf: default
    ipv6_address: "2001:db8:21::201/48"



static_routes:
  - vrf: default
    destination_prefix: "::/0"
    next-hop: "2001:db8:21::1"
