---
# Definition of connected endpoints in the fabric.
servers:
  # Name of the defined server.
  - name: host01
    # Definition of adapters on the server.
    adapters:
        # Name of the server interfaces that will be used in the description of each interface
      - endpoint_ports: [Ethernet1, Ethernet2]
        # Device ports where the server ports are connected.
        switch_ports: [Ethernet4, Ethernet4]
        # Device names where the server ports are connected.
        switches: [leaf01, leaf02]
        # VLANs that will be configured on these ports.
        vlans: 11-12,21-22
        # Native VLAN to be used on these ports.
        native_vlan: 4092
        # L2 mode of the port.
        mode: trunk
        # Spanning tree portfast configuration on this port.
        spanning_tree_portfast: edge
        # Definition of the pair of ports as port channel.
        port_channel:
          # The port-channel name on the endpoint that will be used in the port-channel description.
          endpoint_port_channel: Bond1
          # Port channel mode for LACP.
          mode: active

  - name: host02
    adapters:
      - endpoint_ports: [Ethernet1, Ethernet2]
        switch_ports: [Ethernet4, Ethernet4]
        switches: [leaf03, leaf04]
        vlans: 11-12,21-22
        native_vlan: 4092
        mode: trunk
        spanning_tree_portfast: edge
        port_channel:
          mode: active

  - name: host03
    adapters:
      - endpoint_ports: [Ethernet1, Ethernet2]
        switch_ports: [Ethernet4, Ethernet4]
        switches: [leaf05, leaf06]
        vlans: 11-12,21-22
        native_vlan: 4092
        mode: trunk
        spanning_tree_portfast: edge
        port_channel:
          mode: active

  - name: host04
    adapters:
      - endpoint_ports: [Ethernet1, Ethernet2]
        switch_ports: [Ethernet4, Ethernet4]
        switches: [leaf07, leaf09]
        vlans: 11-12,21-22
        native_vlan: 4092
        mode: trunk
        spanning_tree_portfast: edge
        port_channel:
          mode: active